# Generated by Django 2.2.3 on 2019-07-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordMergeApp', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
